---Revert Version 2.0 By Teixe
function onSay(cid, words, param)
if getPlayerVocation(cid) == 2 then ---Naruto Reverts
doPlayerSetVocation(cid, 1)
local outfit = { lookType = 71 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 3 then
doPlayerSetVocation(cid, 1)
local outfit = { lookType = 71 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 4 then
doPlayerSetVocation(cid, 1)
local outfit = { lookType = 71 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 6 then
doPlayerSetVocation(cid, 5)
local outfit = { lookType = 31 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 7 then
doPlayerSetVocation(cid, 5)
local outfit = { lookType = 31 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 8 then
doPlayerSetVocation(cid, 5)
local outfit = { lookType = 31 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 9 then
doPlayerSetVocation(cid, 5)
local outfit = { lookType = 31 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 10 then
doPlayerSetVocation(cid, 5)
local outfit = { lookType = 31 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")

elseif getPlayerVocation(cid) == 12 then ---Sasuke
doPlayerSetVocation(cid, 11)
local outfit = { lookType = 2 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 13 then
doPlayerSetVocation(cid, 11)
local outfit = { lookType = 2 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 14 then
doPlayerSetVocation(cid, 11)
local outfit = { lookType = 2 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 16 then
doPlayerSetVocation(cid, 15)
local outfit = { lookType = 7 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 17 then
doPlayerSetVocation(cid, 15)
local outfit = { lookType = 7 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 18 then
doPlayerSetVocation(cid, 15)
local outfit = { lookType = 7 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 19 then
doPlayerSetVocation(cid, 15)
local outfit = { lookType = 7 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 20 then
doPlayerSetVocation(cid, 15)
local outfit = { lookType = 7 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")

elseif getPlayerVocation(cid) == 22 then ---Sakura
doPlayerSetVocation(cid, 21)
local outfit = { lookType = 195 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 23 then
doPlayerSetVocation(cid, 21)
local outfit = { lookType = 195 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 24 then
doPlayerSetVocation(cid, 21)
local outfit = { lookType = 195 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 26 then
doPlayerSetVocation(cid, 25)
local outfit = { lookType = 169 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 27 then
doPlayerSetVocation(cid, 25)
local outfit = { lookType = 169 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 28 then
doPlayerSetVocation(cid, 25)
local outfit = { lookType = 169 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 29 then
doPlayerSetVocation(cid, 25)
local outfit = { lookType = 169 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 30 then
doPlayerSetVocation(cid, 25)
local outfit = { lookType = 169 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")

elseif getPlayerVocation(cid) == 32 then ---Gaara
doPlayerSetVocation(cid, 31)
local outfit = { lookType = 53 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 33 then
doPlayerSetVocation(cid, 31)
local outfit = { lookType = 53 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 34 then
doPlayerSetVocation(cid, 31)
local outfit = { lookType = 53 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 36 then
doPlayerSetVocation(cid, 35)
local outfit = { lookType = 62 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 13)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 37 then
doPlayerSetVocation(cid, 35)
local outfit = { lookType = 62 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 12)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 38 then
doPlayerSetVocation(cid, 35)
local outfit = { lookType = 62 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 12)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 39 then
doPlayerSetVocation(cid, 35)
local outfit = { lookType = 62 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 12)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 40 then
doPlayerSetVocation(cid, 35)
local outfit = { lookType = 62 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")


elseif getPlayerVocation(cid) == 42 then ---Lee
doPlayerSetVocation(cid, 41)
local outfit = { lookType = 30 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 43 then
doPlayerSetVocation(cid, 41)
local outfit = { lookType = 30 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 44 then
doPlayerSetVocation(cid, 41)
local outfit = { lookType = 30 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 46 then
doPlayerSetVocation(cid, 45)
local outfit = { lookType = 80 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 47 then
doPlayerSetVocation(cid, 45)
local outfit = { lookType = 80 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 48 then
doPlayerSetVocation(cid, 45)
local outfit = { lookType = 80 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 49 then
doPlayerSetVocation(cid, 45)
local outfit = { lookType = 80 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 50 then
doPlayerSetVocation(cid, 45)
local outfit = { lookType = 80 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")

elseif getPlayerVocation(cid) == 52 then ---Neji
doPlayerSetVocation(cid, 51)
local outfit = { lookType = 102 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 53 then
doPlayerSetVocation(cid, 51)
local outfit = { lookType = 102 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 54 then
doPlayerSetVocation(cid, 51)
local outfit = { lookType = 102 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 56 then
doPlayerSetVocation(cid, 55)
local outfit = { lookType = 107 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 57 then
doPlayerSetVocation(cid, 55)
local outfit = { lookType = 107 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 58 then
doPlayerSetVocation(cid, 55)
local outfit = { lookType = 107 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 59 then
doPlayerSetVocation(cid, 55)
local outfit = { lookType = 107 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 60 then
doPlayerSetVocation(cid, 55)
local outfit = { lookType = 107 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")

elseif getPlayerVocation(cid) == 62 then ---Kiba
doPlayerSetVocation(cid, 61)
local outfit = { lookType = 50 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 63 then
doPlayerSetVocation(cid, 61)
local outfit = { lookType = 50 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 64 then
doPlayerSetVocation(cid, 61)
local outfit = { lookType = 50 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 66 then
doPlayerSetVocation(cid, 65)
local outfit = { lookType = 84 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 67 then
doPlayerSetVocation(cid, 65)
local outfit = { lookType = 84 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 68 then
doPlayerSetVocation(cid, 65)
local outfit = { lookType = 84 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 69 then
doPlayerSetVocation(cid, 65)
local outfit = { lookType = 84 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 70 then
doPlayerSetVocation(cid, 65)
local outfit = { lookType = 84 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")

elseif getPlayerVocation(cid) == 72 then ---Itachi
doPlayerSetVocation(cid, 71)
local outfit = { lookType = 96 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 73 then
doPlayerSetVocation(cid, 71)
local outfit = { lookType = 96 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 74 then
doPlayerSetVocation(cid, 71)
local outfit = { lookType = 96 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 76 then
doPlayerSetVocation(cid, 75)
local outfit = { lookType = 99 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 77 then
doPlayerSetVocation(cid, 75)
local outfit = { lookType = 99 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 78 then
doPlayerSetVocation(cid, 75)
local outfit = { lookType = 99 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 79 then
doPlayerSetVocation(cid, 75)
local outfit = { lookType = 99 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 80 then
doPlayerSetVocation(cid, 75)
local outfit = { lookType = 99 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")

elseif getPlayerVocation(cid) == 82 then ---Kakashi
doPlayerSetVocation(cid, 81)
local outfit = { lookType = 9 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 83 then
doPlayerSetVocation(cid, 81)
local outfit = { lookType = 9 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 84 then
doPlayerSetVocation(cid, 81)
local outfit = { lookType = 9 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 86 then
doPlayerSetVocation(cid, 85)
local outfit = { lookType = 289 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 87 then
doPlayerSetVocation(cid, 85)
local outfit = { lookType = 289 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 88 then
doPlayerSetVocation(cid, 85)
local outfit = { lookType = 289 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 89 then
doPlayerSetVocation(cid, 85)
local outfit = { lookType = 289 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
elseif getPlayerVocation(cid) == 90 then
doPlayerSetVocation(cid, 85)
local outfit = { lookType = 289 , lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0, lookAddons = 0}
doSetCreatureOutfit(cid, outfit, -1)
doSendMagicEffect(getCreaturePosition(cid), 24)
doPlayerSendCancel(cid, "You revert!")
else
doPlayerSendCancel(cid, "You can not revert.")
end

end
